name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21
      
    - name: Install Dependencies
      run: go mod download

    - name: Build
      run: go build -o location-project .
    
    - name: Run Tests
      run: go test ./...
    
    - name: Build Docker Image
      run: docker build -t nazar03/location-project .
    
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    
    - name: Push Docker Image
      run: docker tag location-project ${{ secrets.DOCKER_USERNAME }}/location-project